version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/inventorydb
    networks:
      - inventory-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
